// Copyright (c) Stefano Cristiano
// SPDX-License-Identifier: MIT
#pragma once

#include "../../Libraries/Common/Result.h"

namespace SC
{
namespace Tools
{
/// @brief Stable failures owned by the SC-package tool. Values are append-only.
enum class PackageError : uint32_t
{
    UnknownPackage = 1,
    InstallHandlerMissing,
    ReceiptNotFound,
    PackageNameRequired,
    UnsupportedAction,
    DuplicateRegistryEntry,
    RegistryCapacityExceeded,
    CopySourceDirectoryMissing,
    InstallDirectoryMissing,
    RecipePhaseUnknown,
    RecipePhaseHandlerMissing,
    ExportPathMissing,
    ExportPathAbsolute,
    ExportPathEscapesRoot,
    ExportPathTooDeep,
    SourceHashMalformed,
    SourceHashAlgorithmUnsupported,
    SourceHashDigestMissing,
    ReceiptEncodingFailed,
    ReceiptMalformed,
    ReceiptSchemaUnsupported,
    ReceiptNameMissing,
    DuplicateExport,
    ExportNotFound,
    RepairUnsupportedOnHost,
    RepairRootMissing,
    PackageLayoutIncomplete,
    RepairUnsupported,
    ReceiptVersionMissing,
    ReceiptSourceMissing,
    ReceiptInstallRootMissing,
    ReceiptValidationFailed,
    ExportKindMissing,
    ExportNameMissing,
    ExportFileMissing,
    RegistryExportMissing,
    ReceiptIdentityMismatch,
    LockEncodingFailed,
    ArchiveListingFailed,
    ArchiveEmpty,
    ArchiveRootMissing,
    ArchiveExtractionFailed,
    ExtractedRootMissing,
    ImportDirectoryValueMissing,
    RunnerPathValueMissing,
    UnknownInstallOption,
    UnexpectedInstallArgument,
    PackageDirectoryMissing,
    VersionDirectoryMissing,
    HostCommandUnavailable,
    ArchiveContainerExtractionFailed,
    ArchivePayloadExtractionFailed,
    ArchivePayloadUnsupported,
    MetadataDownloadFailed,
    MetadataDecompressionFailed,
    PackageIndexFieldMissing,
    PackageMetadataNotFound,
    PackageMetadataHashMissing,
    RunnerUnavailable,
    EnvironmentVariableNameNotTerminated,
    InstallerHostUnsupported,
    RunnerArchitectureUnsupported,
    RunnerExecutableMissing,
    RunnerProbeFailed,
    RunnerIdentityMismatch,
    RunnerSetMissing,
    Intel64RunnerMissing,
    Arm64RunnerMissing,
    ImportDirectoryMissing,
    ToolchainCompileFailed,
    ToolchainObjectMissing,
    ToolchainLinkFailed,
    ToolchainExecutableMissing,
    InstallerArchitectureUnsupported,
    PackageArchiveUnavailable,
    ToolVersionMalformed,
    ToolVersionMismatch,
    ToolIdentityMismatch,
    HostToolUnavailable,
    ToolProbeFailed,
    ArchiverProbeFailed,
    ToolMetadataMissing,
    ToolTargetUnsupported,
    ToolTargetMismatch,
    PackageSetupFailed,
    RequiredSourceMissing,
    PackageBuildFailed,
    ToolchainRunFailed,
    PackageBuildArtifactMissing,
    RunnerVersionMismatch,
    PackageCopyFailed,
    PackageDownloadFailed,
    HostCommandFailed,
    SourceHashMismatch,
    DownloadVersionMissing,
    DownloadPlatformMissing,
    DownloadURLMissing,
    DownloadHashMissing,
    SourceCloneFailed,
    SourceRepositoryInitFailed,
    SourceRemoteConfigurationFailed,
    SourceFetchFailed,
    SourceRevisionCheckoutFailed,
    SourceRevisionProbeFailed,
    SourceRevisionMismatch,
    ToolchainIncludesMissing,
    SystemApiIncludesMissing,
    SystemSharedIncludesMissing,
    SystemRuntimeIncludesMissing,
    SystemProjectionIncludesMissing,
    SystemCppProjectionIncludesMissing,
    Intel64ToolchainLibrariesMissing,
    Intel64SystemApiLibrariesMissing,
    Intel64SystemRuntimeLibrariesMissing,
    Intel64CompilerMissing,
    Intel64LinkerMissing,
    Intel64ArchiverMissing,
    Arm64ToolchainLibrariesMissing,
    Arm64SystemApiLibrariesMissing,
    Arm64SystemRuntimeLibrariesMissing,
    Arm64CompilerMissing,
    Arm64LinkerMissing,
    Arm64ArchiverMissing,
    RunnerCrashDialogConfigurationFailed,
    RunnerFirstChanceConfigurationFailed,
    RunnerMenuServiceConfigurationFailed,
};

static constexpr ResultCategory PackageResultCategory = ResultCategory(22);
} // namespace Tools
} // namespace SC
