// Copyright (c) Stefano Cristiano
// SPDX-License-Identifier: MIT
#pragma once

#include "../Common/Result.h"

namespace SC
{
//! @addtogroup group_http_client
//! @{

/// @brief Stable portable failures owned by HttpClient. Values are append-only.
enum class HttpClientError : uint32_t
{
    RequestHeaderNameEmpty = 1,
    RequestHeaderNameInvalid,
    RequestHeaderValueInvalid,
    RequestTransferEncodingForbidden,
    RequestChunkedContentLengthConflict,
    RequestFixedBodyProviderUnexpected,
    RequestFixedBodySizeMismatch,
    RequestStreamInlineBytesUnexpected,
    RequestStreamProviderMissing,
    RequestChunkedDeclaredSizeInvalid,
    RequestBodyFramingInvalid,
    RequestUrlEmpty,
    RequestUrlUnsafe,
    RequestUrlSchemeUnsupported,
    RequestUrlHostEmpty,
    RequestMethodInvalid,
    RequestRedirectModeInvalid,
    RequestProtocolPreferenceInvalid,
    RequestTlsCaPathInvalid,
    RequestRedirectMethodInvalid,
    RequestRedirectBodyNotReplayable,
    ProxyModeInvalid,
    ProxyUrlEmpty,
    ProxyUrlSchemeUnsupported,
    ProxyUrlUnsafe,
    ProxyUrlHostEmpty,
    ProxyUrlPathUnsupported,
    ProxyAuthorizationInvalid,
    ProxyBypassListInvalid,
    ProxyUrlWithoutHttpMode,
    ProxyAuthorizationWithoutHttpMode,
    ProxyBypassListWithoutHttpMode,
    RedirectPolicyUnsupported,
    Http11OnlyUnsupported,
    Http2PreferredUnsupported,
    Http2RequiredUnsupported,
    TlsDisablePeerVerificationUnsupported,
    TlsCustomCaPathUnsupported,
    NoProxyPolicyUnsupported,
    HttpProxyPolicyUnsupported,
    ProxyAuthorizationUnsupported,
    ProxyBypassListUnsupported,
    RequiredBackendUnavailable,
    RequiredFeatureUnsupported,
    ClientAlreadyInitialized,
    OperationClientNotInitialized,
    OperationAlreadyInitialized,
    ResponseBuffersMissing,
    ResponseBufferMemoryTooSmall,
    ResponseBufferEmpty,
    OperationEventQueueMissing,
    OperationResponseHeadersMissing,
    OperationResponseMetadataMissing,
    OperationNotInitialized,
    OperationRequestInFlight,
    RequestBodyDestinationEmpty,
    RequestBodyProviderOverflow,
    RequestBodyProviderStalled,
    RequestBodyDeclaredSizeExceeded,
    RequestBodyDeclaredSizeIncomplete,
    ResponseBufferCapacityInsufficient,
    RequestCancelled,
    ResponseBufferIndexInvalid,
    OperationResponseMissing,
    ResponseMetadataTooSmall,
    BlockingResponseBodyBufferTooSmall,
    PlatformUnsupported,
    ContentCodingListEmpty,
    ContentCodingUnknown,
    AcceptEncodingOutputTooSmall,
    SchedulerAlreadyInitialized,
    SchedulerOperationsMissing,
    SchedulerReadyStorageTooSmall,
    SchedulerOperationNull,
    SchedulerOperationNotInitialized,
    SchedulerNotInitialized,
    SchedulerOperationNotRegistered,
    AsyncAlreadyInitialized,
    AsyncResponseBuffersMissing,
    AsyncResponseReadQueueMissing,
    AsyncRequestWriteQueueMissing,
    AsyncNotInitialized,
    AsyncRequestBodyPoolMissing,
    AsyncRequestBodySinkOwnerMissing,
    AsyncRequestBodySinkDestroyed,
    SessionAlreadyInitialized,
    SessionRequestHeadersMissing,
    SessionNotInitialized,
    SessionStateInvalid,
    SessionCopySpanMismatch,
    SessionStateStorageTooSmall,
    SessionRequestHeaderStorageTooSmall,
    SessionHeaderScratchTooSmall,
    SessionAuthOriginMissing,
    SessionAuthorizationMissing,
    SessionAuthorizationInvalid,
    SessionAuthOriginInvalid,
    SessionAuthOriginPathUnsupported,
    SessionAuthCacheFull,
    SessionBasicUsernameMissing,
    SessionBasicUsernameColonInvalid,
    SessionBasicOutputTooSmall,
    SessionAuthChallengeTargetInvalid,
    SessionAuthResponseStatusInvalid,
    SessionBasicChallengeMissing,
    SessionRequestUrlInvalid,
    SessionCookieCacheFull,
    SessionRetryAttemptsInvalid,
    ResponseHeadersTooSmall,
    TransportFailed,
    RequestUrlConversionFailed,
    RequestUrlInvalid,
    BackendScratchTooSmall,
    RequestBodyStreamUnavailable,
    RequestTaskUnavailable,
};

static constexpr ResultCategory HttpClientResultCategory = ResultCategory(18);

//! @}
} // namespace SC
